language: go
go:
- 1.x
install:
- go get github.com/tcnksm/ghr
- go get github.com/axw/gocov/gocov
- go get github.com/karalabe/xgo
- mkdir dist

script:
# Downloads deps automatically. No need to add manually.
- go list -f '{{.Deps}}' | tr "[" " " | tr "]" " " | xargs go list -e -f '{{if not .Standard}}{{.ImportPath}}{{end}}' | grep -v 'github.com/ewhal/nyaa' | xargs go get -v
- go build
- cd dist
- xgo github.com/ewhal/nyaa
- ghr --username ewhal --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
