version: '3'
services:
  pantsu:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    command: ./deploy/init.sh
    depends_on: 
      - pantsu_db
    env_file:
      - mysql.env
    environment:
      - PANTSU_INTERNAL_PORT=${PANTSU_INTERNAL_PORT}
    links:
      - pantsu_db
    ports:
      # 0.0.0.0 makes it accessible to the network
      # You may want to remove it to make pantsu available only
      # to localhost
      - 0.0.0.0:${PANTSU_EXTERNAL_PORT}:${PANTSU_INTERNAL_PORT}
    volumes:
      - "${GOPATH}:/go/"
      - "./..:/nyaa"

  pantsu_db:
    env_file:
      - mysql.env
    image: mysql:5.7.18
    volumes:
      - "./../${PANTSU_MYSQL_DBFILE}:/docker-entrypoint-initdb.d/${PANTSU_MYSQL_DBFILE}"

  pantsu_db_1:
    image: mysql:5.7.18
    env_file:
      - mysql.env
    links:
      - pantsu_db
